const { spawn } = require('node:child_process');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const CHROME='C:/Program Files/Google/Chrome/Application/chrome.exe';
const URL_='http://127.0.0.1:8326/#/course-resources';
const TOKEN='L1Q8ITTnkF4CUIQI_q3RZ3e5VXbx1O3cqfgUDmhMuEU';
const OUT='D:/Program/Ai-Test/frontend-src/_shots-live/export-modal.png';
const PORT=9477; const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'shx-'));
  const proc=spawn(CHROME,['--headless=new','--disable-gpu','--no-first-run','--force-device-scale-factor=2','--remote-debugging-port='+PORT,'--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
  for(let i=0;i<80;i++){try{const r=await fetch('http://127.0.0.1:'+PORT+'/json/version');if(r.ok)break;}catch{}await sleep(250);}
  const t=await(await fetch('http://127.0.0.1:'+PORT+'/json/new?about:blank',{method:'PUT'})).json();
  const ws=new WebSocket(t.webSocketDebuggerUrl);
  await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true});});
  let id=0;const pend=new Map();
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pend.has(m.id)){const{resolve,reject}=pend.get(m.id);pend.delete(m.id);m.error?reject(new Error(JSON.stringify(m.error))):resolve(m.result);}});
  const send=(method,params)=>new Promise((resolve,reject)=>{const i=++id;pend.set(i,{resolve,reject});ws.send(JSON.stringify({id:i,method,params:params||{}}));});
  const evalJs=async(expr)=>{const r=await send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||'eval');return r.result.value;};
  await Promise.all([send('Page.enable'),send('Runtime.enable')]);
  const [name,...rest]=('pbl_session='+TOKEN).split('=');
  await send('Network.setCookie',{name,value:rest.join('='),domain:'127.0.0.1',path:'/'});
  await send('Emulation.setDeviceMetricsOverride',{width:1600,height:1100,deviceScaleFactor:2,mobile:false});
  await send('Page.navigate',{url:URL_});
  await sleep(9000);
  await evalJs(`document.querySelector('#exportDataBtn').click()`);
  await sleep(1200);
  const data=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  fs.writeFileSync(OUT,Buffer.from(data.data,'base64'));
  console.log('saved',OUT);
  ws.close();proc.kill();process.exit(0);
})().catch(e=>{console.error('FATAL',e.message);process.exit(1);});
